version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ozzadar
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - C:\Users\ozzadar\db_volume:/data/db
    ports:
      - "27017:27017"

volumes:
  db_volume:
    driver: local